language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
deploy:
  provider: rubygems
  api_key:
    secure: sboUxR/0/C5mWB8gchQ4omb+HVwjwR4jcbEFLWpvPFHQCyMB9EfOC5rQRj0MDWjDUcA0xJWcbHcpYXnBY+OqUFEbdf2xj7pB8/kGJHk/gTaRysf8mNjEp4dG1BHZuAQpSivNAKWvWCmvZQfES87iP2dOw2o2J6eMker/zFD9kEY=
  gem: redis-store-testing
  on:
    tags: true
    repo: redis-store/testing
